/* London Tube, Explained
 * -----------------------------------------------------------------------
 * A geographic map of the London Underground that flies you between
 * stations along the fastest route and tells you where each name came from.
 *
 * Data lives in data/network.js (LINES, STATIONS, EDGES, TRANSFERS) and
 * data/etymology.js (ETYMOLOGY).
 */
(function () {
  'use strict';

  var WALK = { name: 'Walk', colour: '#6b7580' };
  var MAP_W = 1000;          // map width in user units, whichever layout is up
  /* how wide the "parked at a station" view is, measured in typical gaps
   * between adjacent stations — the schematic spaces things evenly, so it
   * can afford to show more of them */
  var STATION_ZOOM = { geographic: 4.0, schematic: 5.6 };
  var CHANGE_PENALTY = 6;    // minutes added for changing line
  var TRAIN_SCALE = 1.35;

  function lineInfo(id) { return id === 'walk' ? WALK : LINES[id]; }

  /* ------------------------------------------------------------------
   * Layouts
   *
   * Two ways of placing the same 270 stations: where they actually are,
   * and Beck's octilinear diagram (generated by tools/schematic.js).
   * Both are normalised to the same width so the camera constants hold.
   * ---------------------------------------------------------------- */

  var ids = Object.keys(STATIONS);
  var P = {};                 // live positions, whatever the current layout
  var layoutMode = 'schematic';

  function normalise(raw) {
    var minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity, id;
    for (id in raw) {
      if (raw[id].x < minX) minX = raw[id].x;
      if (raw[id].x > maxX) maxX = raw[id].x;
      if (raw[id].y < minY) minY = raw[id].y;
      if (raw[id].y > maxY) maxY = raw[id].y;
    }
    var scale = MAP_W / (maxX - minX);
    var cx = (minX + maxX) / 2, cy = (minY + maxY) / 2;
    var out = {};
    for (id in raw) {
      out[id] = { x: (raw[id].x - cx) * scale, y: (raw[id].y - cy) * scale };
    }
    return out;
  }

  var LAYOUTS = {
    geographic: (function () {
      var lat0 = 0, i;
      for (i = 0; i < ids.length; i++) lat0 += STATIONS[ids[i]].lat;
      lat0 /= ids.length;
      var k = Math.cos(lat0 * Math.PI / 180), raw = {};
      for (i = 0; i < ids.length; i++) {
        raw[ids[i]] = { x: STATIONS[ids[i]].lon * k, y: -STATIONS[ids[i]].lat };
      }
      return normalise(raw);
    })(),
    schematic: (function () {
      var raw = {};
      for (var i = 0; i < ids.length; i++) {
        var p = SCHEMATIC[ids[i]];
        raw[ids[i]] = { x: p[0], y: p[1] };
      }
      return normalise(raw);
    })()
  };

  /* how far apart a typical pair of adjacent stations sits, per layout —
   * the camera uses it to pick a sensible "parked at a station" zoom */
  var LAYOUT_STEP = {};
  Object.keys(LAYOUTS).forEach(function (mode) {
    var L = LAYOUTS[mode];
    var lens = EDGES.map(function (e) {
      return Math.hypot(L[e[0]].x - L[e[1]].x, L[e[0]].y - L[e[1]].y);
    }).sort(function (a, b) { return a - b; });
    LAYOUT_STEP[mode] = lens[Math.floor(lens.length / 2)];
  });

  function setPositions(mode) {
    var L = LAYOUTS[mode];
    for (var i = 0; i < ids.length; i++) P[ids[i]] = { x: L[ids[i]].x, y: L[ids[i]].y };
  }
  setPositions(layoutMode);

  function computeBounds() {
    var b = { x0: Infinity, x1: -Infinity, y0: Infinity, y1: -Infinity };
    ids.forEach(function (id) {
      var p = P[id];
      b.x0 = Math.min(b.x0, p.x); b.x1 = Math.max(b.x1, p.x);
      b.y0 = Math.min(b.y0, p.y); b.y1 = Math.max(b.y1, p.y);
    });
    return b;
  }
  var bounds = computeBounds();
  var stationW = LAYOUT_STEP[layoutMode] * STATION_ZOOM[layoutMode];

  /* ------------------------------------------------------------------
   * Graph
   * ---------------------------------------------------------------- */

  var adj = {};
  ids.forEach(function (id) { adj[id] = []; });

  EDGES.forEach(function (e) {
    adj[e[0]].push({ to: e[1], line: e[2], t: e[3] });
    adj[e[1]].push({ to: e[0], line: e[2], t: e[3] });
  });
  TRANSFERS.forEach(function (e) {
    adj[e[0]].push({ to: e[1], line: 'walk', t: e[2] });
    adj[e[1]].push({ to: e[0], line: 'walk', t: e[2] });
  });

  /* ------------------------------------------------------------------
   * Edge geometry
   *
   * Every edge is a polyline. On the geographic map that is one straight
   * chord. On the schematic it is routed octilinearly: the layout gets 94%
   * of edges onto an exact 45-degree multiple, and the rest are drawn with
   * a single bend so that no line is ever seen at an odd angle.
   *
   * Where several lines share a pair of stations they are fanned out either
   * side of the centre line, which means offsetting a polyline — each
   * segment shifts along its own normal and consecutive segments are joined
   * at the intersection of the shifted lines.
   * ---------------------------------------------------------------- */

  var OCT = Math.PI / 4;
  var SNAP = 5 * Math.PI / 180;   // closer than this to a 45-degree multiple: leave it

  function routeEdge(a, b, octilinear) {
    if (!octilinear) return [[a.x, a.y], [b.x, b.y]];
    var dx = b.x - a.x, dy = b.y - a.y;
    var th = Math.atan2(dy, dx);
    var off = ((th % OCT) + OCT) % OCT;
    if (Math.min(off, OCT - off) < SNAP) return [[a.x, a.y], [b.x, b.y]];

    var adx = Math.abs(dx), ady = Math.abs(dy);
    var sx = dx < 0 ? -1 : 1, sy = dy < 0 ? -1 : 1;
    var run = Math.abs(adx - ady), diag = Math.min(adx, ady);
    var bend1, bend2;
    if (adx > ady) {                       // mostly horizontal
      bend1 = [a.x + sx * run, a.y];               // straight first, then 45
      bend2 = [a.x + sx * diag, a.y + sy * diag];  // 45 first, then straight
    } else {                               // mostly vertical
      bend1 = [a.x, a.y + sy * run];
      bend2 = [a.x + sx * diag, a.y + sy * diag];
    }
    /* put the corner wherever it is least likely to sit on top of a station */
    return [[a.x, a.y], clearestBend(bend1, bend2, a, b), [b.x, b.y]];
  }

  function clearestBend(c1, c2, a, b) {
    function clearance(c) {
      var worst = Infinity;
      for (var i = 0; i < ids.length; i++) {
        var p = P[ids[i]];
        if ((p.x === a.x && p.y === a.y) || (p.x === b.x && p.y === b.y)) continue;
        var d = Math.hypot(p.x - c[0], p.y - c[1]);
        if (d < worst) worst = d;
      }
      return worst;
    }
    return clearance(c1) >= clearance(c2) ? c1 : c2;
  }

  /* shift a polyline sideways by o, keeping the corners tight */
  function offsetPolyline(pts, o) {
    if (!o) return pts;
    var n = pts.length, i;
    var norms = [];
    for (i = 0; i < n - 1; i++) {
      var dx = pts[i + 1][0] - pts[i][0], dy = pts[i + 1][1] - pts[i][1];
      var L = Math.hypot(dx, dy) || 1;
      norms.push([-dy / L, dx / L]);
    }
    var out = [[pts[0][0] + norms[0][0] * o, pts[0][1] + norms[0][1] * o]];
    for (i = 1; i < n - 1; i++) {
      var p = pts[i];
      var n1 = norms[i - 1], n2 = norms[i];
      var a1 = [p[0] + n1[0] * o, p[1] + n1[1] * o];
      var d1 = [pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]];
      var a2 = [p[0] + n2[0] * o, p[1] + n2[1] * o];
      var d2 = [pts[i + 1][0] - pts[i][0], pts[i + 1][1] - pts[i][1]];
      var den = d1[0] * d2[1] - d1[1] * d2[0];
      if (Math.abs(den) < 1e-9) { out.push(a1); continue; }
      var t = ((a2[0] - a1[0]) * d2[1] - (a2[1] - a1[1]) * d2[0]) / den;
      out.push([a1[0] + d1[0] * t, a1[1] + d1[1] * t]);
    }
    out.push([pts[n - 1][0] + norms[n - 2][0] * o, pts[n - 1][1] + norms[n - 2][1] * o]);
    return out;
  }

  function pathFrom(pts) {
    var d = 'M' + pts[0][0].toFixed(2) + ' ' + pts[0][1].toFixed(2);
    for (var i = 1; i < pts.length; i++) {
      d += 'L' + pts[i][0].toFixed(2) + ' ' + pts[i][1].toFixed(2);
    }
    return d;
  }

  function polyLength(pts) {
    var L = 0;
    for (var i = 1; i < pts.length; i++) {
      L += Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]);
    }
    return L;
  }

  /* where you are, and which way you face, a fraction t along a polyline */
  function walk(pts, t) {
    var total = polyLength(pts), want = total * Math.max(0, Math.min(1, t)), acc = 0;
    for (var i = 1; i < pts.length; i++) {
      var seg = Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]);
      if (acc + seg >= want || i === pts.length - 1) {
        var f = seg ? (want - acc) / seg : 0;
        return {
          x: pts[i - 1][0] + (pts[i][0] - pts[i - 1][0]) * f,
          y: pts[i - 1][1] + (pts[i][1] - pts[i - 1][1]) * f,
          angle: Math.atan2(pts[i][1] - pts[i - 1][1], pts[i][0] - pts[i - 1][0]) * 180 / Math.PI
        };
      }
      acc += seg;
    }
    return { x: pts[0][0], y: pts[0][1], angle: 0 };
  }

  var geom = {};                    // "a|b|line" -> geometry
  var geomList = [];

  (function collectEdges() {
    var groups = {};
    EDGES.forEach(function (e) {
      var key = e[0] < e[1] ? e[0] + '|' + e[1] : e[1] + '|' + e[0];
      (groups[key] || (groups[key] = [])).push(e);
    });
    Object.keys(groups).forEach(function (key) {
      var list = groups[key];
      list.sort(function (a, b) { return a[2] < b[2] ? -1 : 1; });
      var pair = key.split('|');
      list.forEach(function (e, i) {
        var g = {
          a: pair[0], b: pair[1], line: e[2],
          off: i - (list.length - 1) / 2,
          pts: null, el: null
        };
        geom[pair[0] + '|' + pair[1] + '|' + e[2]] = g;
        geom[pair[1] + '|' + pair[0] + '|' + e[2]] = g;
        geomList.push(g);
      });
    });
  })();

  function buildGeometry(octilinear) {
    for (var i = 0; i < geomList.length; i++) {
      var g = geomList[i];
      g.pts = routeEdge(P[g.a], P[g.b], octilinear);
    }
  }
  buildGeometry(layoutMode === 'schematic');

  function edgePath(g, spread) {
    return pathFrom(offsetPolyline(g.pts, g.off * spread));
  }

  /* the same offset polyline, but running the way the train goes: offset
   * first (the normal is defined on the canonical a-to-b order), then flip */
  function ridePath(g, spread, forward) {
    var pts = offsetPolyline(g.pts, g.off * spread);
    return forward ? pts : pts.slice().reverse();
  }

  /* ------------------------------------------------------------------
   * Routing — Dijkstra over (station, line) states so that changing
   * line carries a real cost and the router prefers to stay put.
   * ---------------------------------------------------------------- */

  function route(from, to) {
    if (from === to) return [];
    var dist = {}, prev = {}, seen = {};
    var heap = [];

    function push(node, d) {
      heap.push({ n: node, d: d });
      var i = heap.length - 1;
      while (i > 0) {
        var p = (i - 1) >> 1;
        if (heap[p].d <= heap[i].d) break;
        var t = heap[p]; heap[p] = heap[i]; heap[i] = t;
        i = p;
      }
    }
    function pop() {
      var top = heap[0], last = heap.pop();
      if (heap.length) {
        heap[0] = last;
        var i = 0;
        for (;;) {
          var l = 2 * i + 1, r = l + 1, m = i;
          if (l < heap.length && heap[l].d < heap[m].d) m = l;
          if (r < heap.length && heap[r].d < heap[m].d) m = r;
          if (m === i) break;
          var t = heap[m]; heap[m] = heap[i]; heap[i] = t;
          i = m;
        }
      }
      return top;
    }

    adj[from].forEach(function (e) {
      var key = e.to + '|' + e.line;
      var cost = e.t + (e.line === 'walk' ? CHANGE_PENALTY : 0);
      if (dist[key] === undefined || cost < dist[key]) {
        dist[key] = cost;
        prev[key] = { station: from, line: null, edge: e };
        push(key, cost);
      }
    });

    var goal = null;
    while (heap.length) {
      var cur = pop();
      if (seen[cur.n]) continue;
      seen[cur.n] = true;
      var parts = cur.n.split('|');
      var st = parts[0], ln = parts[1];
      if (st === to) { goal = cur.n; break; }

      adj[st].forEach(function (e) {
        var key = e.to + '|' + e.line;
        if (seen[key]) return;
        var cost = cur.d + e.t + (e.line !== ln ? CHANGE_PENALTY : 0);
        if (dist[key] === undefined || cost < dist[key]) {
          dist[key] = cost;
          prev[key] = { station: st, line: ln, edge: e };
          push(key, cost);
        }
      });
    }
    if (!goal) return null;

    var steps = [], node = goal;
    while (node) {
      var p = prev[node];
      var parts = node.split('|');
      steps.push({ from: p.station, to: parts[0], line: parts[1], t: p.edge.t });
      node = p.line === null ? null : p.station + '|' + p.line;
    }
    steps.reverse();
    return steps;
  }

  /* Collapse the step list into human legs: "Victoria line to Oxford Circus". */
  function legs(steps) {
    var out = [];
    steps.forEach(function (s) {
      var last = out[out.length - 1];
      if (last && last.line === s.line) {
        last.to = s.to; last.stops++; last.t += s.t;
      } else {
        out.push({ line: s.line, from: s.from, to: s.to, stops: 1, t: s.t });
      }
    });
    return out;
  }

  /* ------------------------------------------------------------------
   * SVG scene
   * ---------------------------------------------------------------- */

  var NS = 'http://www.w3.org/2000/svg';
  var svg = document.getElementById('map');
  var gTransfers = document.getElementById('g-transfers');
  var gEdges = document.getElementById('g-edges');
  var gRoute = document.getElementById('g-route');
  var gStations = document.getElementById('g-stations');
  var gLabels = document.getElementById('g-labels');
  var gTrain = document.getElementById('g-train');

  function el(name, attrs) {
    var n = document.createElementNS(NS, name);
    for (var k in attrs) n.setAttribute(k, attrs[k]);
    return n;
  }

  var transferEls = TRANSFERS.map(function (t) {
    var path = el('path', { 'class': 'transfer', 'vector-effect': 'non-scaling-stroke' });
    gTransfers.appendChild(path);
    return { t: t, el: path };
  });
  function drawTransfers() {
    transferEls.forEach(function (x) {
      var pa = P[x.t[0]], pb = P[x.t[1]];
      x.el.setAttribute('d', 'M' + pa.x + ' ' + pa.y + 'L' + pb.x + ' ' + pb.y);
    });
  }
  drawTransfers();

  geomList.forEach(function (g) {
    g.el = el('path', {
      'class': 'edge',
      stroke: lineInfo(g.line).colour,
      'vector-effect': 'non-scaling-stroke',
      'stroke-width': 3.4
    });
    gEdges.appendChild(g.el);
  });

  var gPlan = el('g', {}), gDone = el('g', {});
  gRoute.appendChild(gPlan);
  gRoute.appendChild(gDone);

  var dots = {}, labels = {};
  ids.forEach(function (id) {
    var s = STATIONS[id], p = P[id];
    var c = el('circle', {
      'class': 'stop ' + (s.lines.length > 1 ? 'interchange' : 'plain'),
      cx: p.x, cy: p.y, r: 3,
      'stroke-width': 1.2, 'vector-effect': 'non-scaling-stroke'
    });
    c.addEventListener('click', function (ev) { ev.stopPropagation(); goTo(id); });
    c.addEventListener('mouseenter', function () { c.setAttribute('r', dotR(id) * 1.6); });
    c.addEventListener('mouseleave', function () { c.setAttribute('r', dotR(id)); });
    gStations.appendChild(c);
    dots[id] = c;

    var t = el('text', {
      'class': 'label' + (s.lines.length > 1 ? ' major' : ''),
      x: p.x, y: p.y
    });
    t.textContent = s.name;
    gLabels.appendChild(t);
    labels[id] = t;
  });

  var train = el('g', { id: 'train' });
  train.innerHTML =
    '<rect x="-11.4" y="-6.6" width="22.8" height="13.2" rx="4.8" fill="#fff"' +
    ' stroke="#14181c" stroke-width="1.1"/>' +
    '<rect x="-9.6" y="-4.8" width="19.2" height="9.6" rx="3.4" fill="#1f262e"/>' +
    '<rect x="-7.6" y="-3" width="4.6" height="4" rx="1.2" fill="#9bdcff"/>' +
    '<rect x="-1.6" y="-3" width="4.6" height="4" rx="1.2" fill="#9bdcff"/>' +
    '<rect x="4.4" y="-3" width="3.4" height="4" rx="1.2" fill="#ffd300"/>' +
    '<circle cx="9.4" cy="0" r="1.5" fill="#ffd300"/>';
  train.style.display = 'none';
  gTrain.appendChild(train);

  /* ------------------------------------------------------------------
   * Camera
   * ---------------------------------------------------------------- */

  var view = { cx: 0, cy: 0, w: MAP_W * 1.12 };
  var anim = null;      // camera tween
  var unitsPerPx = 1;
  var lastSpread = -1;

  function overviewWidth() {
    var pad = 1.12;
    var w = (bounds.x1 - bounds.x0) * pad;
    var h = (bounds.y1 - bounds.y0) * pad;
    var ratio = svg.clientHeight / svg.clientWidth || 0.6;
    return Math.max(w, h / ratio);
  }
  function overview() {
    return {
      cx: (bounds.x0 + bounds.x1) / 2,
      cy: (bounds.y0 + bounds.y1) / 2,
      w: overviewWidth()
    };
  }

  function dotR(id) {
    var base = STATIONS[id].lines.length > 1 ? 3.6 : 2.5;
    if (id === current) base = 4.6;
    return base * unitsPerPx;
  }

  function applyCam() {
    var cw = svg.clientWidth || 1, ch = svg.clientHeight || 1;
    var h = view.w * ch / cw;
    svg.setAttribute('viewBox',
      (view.cx - view.w / 2) + ' ' + (view.cy - h / 2) + ' ' + view.w + ' ' + h);
    unitsPerPx = view.w / cw;

    var spread = 3.1 * unitsPerPx;
    if (lastSpread < 0 || Math.abs(spread - lastSpread) / lastSpread > 0.004) {
      lastSpread = spread;
      geomList.forEach(function (g) { g.el.setAttribute('d', edgePath(g, spread)); });
      routeParts.forEach(function (rp) {
        var ride = ridePath(rp.g, spread, rp.forward);
        rp.plan.setAttribute('d', edgePath(rp.g, spread));
        rp.done.setAttribute('d', pathFrom(ride));
        rp.len = polyLength(ride);
      });
      ids.forEach(function (id) { dots[id].setAttribute('r', dotR(id)); });
      gLabels.style.fontSize = (11.5 * unitsPerPx) + 'px';
      gLabels.style.strokeWidth = (2.6 * unitsPerPx) + 'px';
    }
    placeTrain();          /* cheap, and it moves on every frame of a journey */
    placeLabels();
  }

  function tweenTo(target, ms, done) {
    var from = { cx: view.cx, cy: view.cy, w: view.w };
    var t0 = performance.now();
    anim = function (now) {
      var p = Math.min(1, (now - t0) / ms);
      var e = p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2;
      view.cx = from.cx + (target.cx - from.cx) * e;
      view.cy = from.cy + (target.cy - from.cy) * e;
      /* interpolate zoom geometrically so it feels linear to the eye */
      view.w = from.w * Math.pow(target.w / from.w, e);
      applyCam();
      if (p >= 1) { anim = null; if (done) done(); }
    };
  }

  var frameJobs = [];
  function loop(now) {
    if (anim) anim(now);
    for (var i = frameJobs.length - 1; i >= 0; i--) {
      if (frameJobs[i](now) === false) frameJobs.splice(i, 1);
    }
    requestAnimationFrame(loop);
  }
  requestAnimationFrame(loop);

  /* ------------------------------------------------------------------
   * Labels — greedy declutter in screen space
   * ---------------------------------------------------------------- */

  var widthRatio = {};
  (function measure() {
    var ctx = document.createElement('canvas').getContext('2d');
    ctx.font = '500 100px ' + getComputedStyle(document.body).fontFamily;
    ids.forEach(function (id) {
      widthRatio[id] = ctx.measureText(STATIONS[id].name).width / 100;
    });
  })();

  var order = ids.slice().sort(function (a, b) {
    var d = STATIONS[b].lines.length - STATIONS[a].lines.length;
    if (d) return d;
    d = parseFloat(STATIONS[a].zone) - parseFloat(STATIONS[b].zone);
    if (d) return d;
    return STATIONS[a].name < STATIONS[b].name ? -1 : 1;
  });

  /* the station you are standing at gets first pick of a label position,
     ahead of even a six-line interchange */
  var labelOrder = order.slice();

  var ANCHORS = [
    { dx: 7, dy: 3.6, anchor: 'start' },
    { dx: -7, dy: 3.6, anchor: 'end' },
    { dx: 0, dy: -8, anchor: 'middle' },
    { dx: 0, dy: 13, anchor: 'middle' }
  ];

  /* The chrome floats over the map, so treat those panels as already-occupied
   * space and let the labels flow around them. */
  var uiPanels = ['title', 'goto', 'panel', 'controls'];
  function uiObstacles() {
    var out = [];
    for (var i = 0; i < uiPanels.length; i++) {
      var node = document.getElementById(uiPanels[i]);
      if (!node || node.hidden) continue;
      var r = node.getBoundingClientRect();
      if (!r.width || !r.height) continue;
      out.push({ x0: r.left - 8, x1: r.right + 8, y0: r.top - 6, y1: r.bottom + 6 });
    }
    return out;
  }

  function placeLabels() {
    var cw = svg.clientWidth || 1, ch = svg.clientHeight || 1;
    var vx = view.cx - view.w / 2;
    var vy = view.cy - (view.w * ch / cw) / 2;
    var fs = 11.5;
    var placed = uiObstacles();
    var margin = 40;

    for (var i = 0; i < labelOrder.length; i++) {
      var id = labelOrder[i], p = P[id], t = labels[id];
      var sx = (p.x - vx) / unitsPerPx, sy = (p.y - vy) / unitsPerPx;

      if (sx < -margin || sx > cw + margin || sy < -margin || sy > ch + margin) {
        t.style.display = 'none';
        continue;
      }
      var w = widthRatio[id] * fs, h = fs * 0.95;
      var forced = (id === current);
      var chosen = null;

      for (var a = 0; a < ANCHORS.length; a++) {
        var A = ANCHORS[a];
        var lx = sx + A.dx, ly = sy + A.dy;
        var x0 = A.anchor === 'start' ? lx : A.anchor === 'end' ? lx - w : lx - w / 2;
        var box = { x0: x0 - 2, x1: x0 + w + 2, y0: ly - h, y1: ly + 3 };
        var hit = false;
        for (var j = 0; j < placed.length; j++) {
          var q = placed[j];
          if (box.x0 < q.x1 && box.x1 > q.x0 && box.y0 < q.y1 && box.y1 > q.y0) { hit = true; break; }
        }
        if (!hit) { chosen = { A: A, box: box }; break; }
      }
      if (!chosen && forced) chosen = { A: ANCHORS[0], box: null };

      if (chosen) {
        if (chosen.box) placed.push(chosen.box);
        t.style.display = '';
        t.setAttribute('x', p.x + chosen.A.dx * unitsPerPx);
        t.setAttribute('y', p.y + chosen.A.dy * unitsPerPx);
        t.setAttribute('text-anchor', chosen.A.anchor);
      } else {
        t.style.display = 'none';
      }
    }
  }

  /* ------------------------------------------------------------------
   * Train
   * ---------------------------------------------------------------- */

  var trainPos = null;      // {x, y, angle}

  function placeTrain() {
    if (!trainPos) return;
    train.setAttribute('transform',
      'translate(' + trainPos.x + ',' + trainPos.y + ') ' +
      'rotate(' + trainPos.angle + ') ' +
      'scale(' + (unitsPerPx * TRAIN_SCALE) + ')');
  }

  function parkTrain(id, angle) {
    var p = P[id];
    /* sit the little train just beside the station dot */
    trainPos = { x: p.x - 30 * unitsPerPx, y: p.y - 26 * unitsPerPx, angle: angle || 0 };
    train.style.display = '';
    placeTrain();
  }

  /* ------------------------------------------------------------------
   * Route rendering + journey animation
   * ---------------------------------------------------------------- */

  var routeParts = [];      // {g, plan, done, len}
  var running = null;
  var whereTrainIs = null;  // last station the train passed, mid-journey

  /* While a journey runs the rest of the map dims, but the lines the journey
   * actually uses keep their colour — so the Victoria blue you are riding and
   * the Bakerloo brown you are about to change onto stay legible as the
   * camera pulls back. */
  function markInvolved(steps) {
    var used = {};
    steps.forEach(function (s) { if (s.line !== 'walk') used[s.line] = true; });
    geomList.forEach(function (g) {
      g.el.classList.toggle('involved', !!used[g.line]);
    });
  }

  function endTravelStyling() {
    gEdges.classList.remove('muted');
    geomList.forEach(function (g) { g.el.classList.remove('involved'); });
  }

  function clearRoute() {
    routeParts = [];
    gPlan.innerHTML = '';
    gDone.innerHTML = '';
    ids.forEach(function (id) { dots[id].classList.remove('on-route'); });
  }

  function drawRoute(steps) {
    clearRoute();
    steps.forEach(function (s) {
      var g = geom[s.from + '|' + s.to + '|' + s.line];
      if (!g) {
        /* a walking transfer: straight, no fan-out */
        g = { a: s.from, b: s.to, off: 0, line: s.line,
              pts: [[P[s.from].x, P[s.from].y], [P[s.to].x, P[s.to].y]] };
      }
      var colour = lineInfo(s.line).colour;
      var plan = el('path', {
        'class': 'route-leg', stroke: colour,
        'vector-effect': 'non-scaling-stroke', 'stroke-width': 7,
        d: edgePath(g, lastSpread)
      });
      var forward = s.from === g.a;
      var ride = ridePath(g, lastSpread, forward);
      var done = el('path', {
        'class': 'route-leg done', stroke: colour,
        'vector-effect': 'non-scaling-stroke', 'stroke-width': 7,
        d: pathFrom(ride)
      });
      done.style.strokeDasharray = '0 100000';
      gPlan.appendChild(plan);
      gDone.appendChild(done);
      routeParts.push({
        g: g, plan: plan, done: done, forward: forward, len: polyLength(ride)
      });
      dots[s.from].classList.add('on-route');
      dots[s.to].classList.add('on-route');
    });
  }

  function travel(steps, arrive) {
    var total = steps.reduce(function (a, s) { return a + s.t; }, 0);
    var ms = Math.max(2000, Math.min(14000, 520 * steps.length + 900));
    var t0 = performance.now();
    markInvolved(steps);
    gEdges.classList.add('muted');

    var travelW = Math.min(overviewWidth() * 0.75,
                           stationW * (1.6 + 0.9 * Math.sqrt(steps.length)));

    running = function (now) {
      var p = Math.min(1, (now - t0) / ms);
      var e = p < 0.5 ? 2 * p * p : 1 - Math.pow(-2 * p + 2, 2) / 2;

      /* find the step we are on, weighted by scheduled minutes */
      var travelled = e * total, acc = 0, i = 0, frac = 0;
      for (i = 0; i < steps.length; i++) {
        if (acc + steps[i].t >= travelled || i === steps.length - 1) {
          frac = Math.min(1, (travelled - acc) / steps[i].t);
          break;
        }
        acc += steps[i].t;
      }

      whereTrainIs = frac > 0.5 ? steps[i].to : steps[i].from;
      var rpNow = routeParts[i];
      var at = walk(ridePath(rpNow.g, lastSpread, rpNow.forward), frac);
      var x = at.x, y = at.y;
      trainPos = { x: x, y: y, angle: at.angle };

      for (var j = 0; j < routeParts.length; j++) {
        var rp = routeParts[j];
        var f = j < i ? 1 : j > i ? 0 : frac;
        rp.done.style.strokeDasharray = (rp.len * f) + ' 100000';
      }

      /* camera: pull back for the ride, close in on arrival */
      var w;
      if (p < 0.12) w = view.w * Math.pow(travelW / view.w, p / 0.12);
      else if (p > 0.86) {
        var q = (p - 0.86) / 0.14;
        w = travelW * Math.pow(stationW / travelW, q);
      } else w = travelW;

      view.cx = x; view.cy = y; view.w = w;
      applyCam();

      if (p >= 1) {
        running = null;
        endTravelStyling();
        arrive();
        return false;
      }
      return true;
    };
    frameJobs.push(running);
  }

  /* ------------------------------------------------------------------
   * Panels
   * ---------------------------------------------------------------- */

  var panel = document.getElementById('panel');
  var panelInner = document.getElementById('panel-inner');
  /* The route card is currently switched off: the element is not in the page.
   * Everything that builds it still works — put the <aside id="journey"> back
   * and it returns. Until then every reference has to tolerate its absence. */
  var journeyBox = document.getElementById('journey');

  function zoneLabel(z) {
    var n = parseFloat(z);
    if (isNaN(n)) return '';
    if (n > 6.5) return 'Beyond zone 6';
    if (n % 1) return 'Zones ' + Math.floor(n) + '/' + Math.ceil(n);
    return 'Zone ' + n;
  }

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function showStation(id) {
    var s = STATIONS[id], e = ETYMOLOGY[id];
    var chips = s.lines.map(function (l) {
      var L = LINES[l];
      var dark = l === 'circle' || l === 'hammersmith' ||
                 l === 'waterloo-city' || l === 'jubilee';
      return '<span class="chip" style="background:' + L.colour + ';color:' +
        (dark ? '#111' : '#fff') + '">' + esc(L.name) + '</span>';
    }).join('');

    /* the chain of recorded forms, oldest first, ending in today's name */
    var chain = '';
    if (e.chain) {
      chain = '<div class="chain">' + e.chain.map(function (form, i) {
        var last = i === e.chain.length - 1;
        return (i ? '<i>&rarr;</i>' : '') +
          '<span' + (last ? ' class="now"' : '') + '>' + esc(form) + '</span>';
      }).join('') + '</div>';
    }

    panelInner.innerHTML =
      '<div class="lines">' + chips + '</div>' +
      '<h2>' + esc(s.name) + '</h2>' +
      '<div class="zone">' + zoneLabel(s.zone) + '</div>' +
      '<p class="gist">' + esc(e.gist) + '</p>' +
      '<p class="body">' + esc(e.text) + '</p>' +
      chain +
      (e.note
        ? '<div class="note"><div class="h">No settled answer</div><p>' +
          esc(e.note) + '</p></div>'
        : '') +
      /* further reading, not a citation — see data/sources.js */
      (SOURCES[id]
        ? '<a class="src' + (SOURCES[id].checked ? ' checked' : '') + '" href="' +
          esc(SOURCES[id].url) + '" target="_blank" rel="noopener noreferrer" title="' +
          (SOURCES[id].checked
            ? 'This article corroborates the derivation given here'
            : 'This article does not discuss the name — further reading only') +
          '">' + (SOURCES[id].checked ? '&#10003; ' : '') +
          'Wikipedia &#8599;</a>'
        : '');
    panel.classList.add('show');
    panel.scrollTop = 0;
  }

  function showJourney(from, to, steps) {
    if (!journeyBox) return;
    if (!steps || !steps.length) { journeyBox.hidden = true; return; }
    var ls = legs(steps);
    var mins = steps.reduce(function (a, s) { return a + s.t; }, 0) +
               (ls.length - 1) * 2;
    var html = '<div class="jt">' + esc(STATIONS[from].name) + ' &rarr; ' +
      esc(STATIONS[to].name) + '</div>';
    ls.forEach(function (l) {
      var L = lineInfo(l.line);
      html += '<div class="leg">' +
        '<span class="bar" style="background:' + L.colour + '"></span>' +
        '<span class="leg-txt">' +
        (l.line === 'walk'
          ? 'Walk to <b>' + esc(STATIONS[l.to].name) + '</b>'
          : '<b>' + esc(L.name) + '</b> to ' + esc(STATIONS[l.to].name) +
            ' &middot; ' + l.stops + ' stop' + (l.stops > 1 ? 's' : '')) +
        '</span></div>';
    });
    html += '<div class="foot">' + (ls.length - 1) + ' change' +
      (ls.length - 1 === 1 ? '' : 's') + ' &middot; about ' + Math.round(mins) +
      ' min</div>';
    journeyBox.innerHTML = html;
    journeyBox.hidden = false;
  }

  /* ------------------------------------------------------------------
   * Going places
   * ---------------------------------------------------------------- */

  var current = null;

  function setCurrent(id) {
    if (current && dots[current]) {
      dots[current].classList.remove('here');
      labels[current].classList.remove('here');
      dots[current].setAttribute('r', dotR(current));
    }
    current = id;
    labelOrder = [id];
    for (var i = 0; i < order.length; i++) if (order[i] !== id) labelOrder.push(order[i]);
    dots[id].classList.add('here');
    labels[id].classList.add('here');
    dots[id].setAttribute('r', dotR(id));
  }

  function goTo(id) {
    if (running) {                      // interrupting a journey in progress
      frameJobs.length = 0;
      running = null;
      endTravelStyling();
      if (whereTrainIs) { setCurrent(whereTrainIs); whereTrainIs = null; }
      clearRoute();
    }
    if (STATIONS[id]) {
      search.value = STATIONS[id].name;
      combo.classList.add('filled');
    }
    document.getElementById('results').hidden = true;
    document.getElementById('search').blur();
    hint.classList.remove('show');

    if (!current) {                       // first arrival: just fly in
      setCurrent(id);
      panel.classList.remove('show');
      parkTrain(id);
      tweenTo({ cx: P[id].x, cy: P[id].y, w: stationW }, 2200, function () {
        parkTrain(id);
        showStation(id);
      });
      return;
    }
    if (id === current) {
      tweenTo({ cx: P[id].x, cy: P[id].y, w: stationW }, 900);
      showStation(id);
      return;
    }

    var steps = route(current, id);
    if (!steps) { showStation(id); setCurrent(id); return; }

    panel.classList.remove('show');
    showJourney(current, id, steps);
    drawRoute(steps);
    anim = null;
    train.style.display = '';

    travel(steps, function () {
      whereTrainIs = null;
      setCurrent(id);
      parkTrain(id);
      showStation(id);
      clearRoute();
      drawRouteFaint(steps);
    });
  }

  /* leave the taken route on the map, faintly, after arrival */
  function drawRouteFaint(steps) {
    steps.forEach(function (s) {
      var g = geom[s.from + '|' + s.to + '|' + s.line] ||
              { a: s.from, b: s.to, off: 0, pts: [[P[s.from].x, P[s.from].y], [P[s.to].x, P[s.to].y]] };
      var path = el('path', {
        'class': 'route-leg done trace', stroke: lineInfo(s.line).colour,
        'vector-effect': 'non-scaling-stroke', 'stroke-width': 6,
        d: edgePath(g, lastSpread)
      });
      gDone.appendChild(path);
      routeParts.push({ g: g, plan: path, done: path, forward: true, len: 0 });
    });
  }

  /* ------------------------------------------------------------------
   * Search box
   * ---------------------------------------------------------------- */

  var search = document.getElementById('search');
  var results = document.getElementById('results');
  var clearBtn = document.getElementById('clear');
  var combo = search.parentNode;
  var hint = document.getElementById('hint');
  var cursor = -1, shown = [];

  function norm(s) {
    return s.toLowerCase().replace(/[^a-z0-9 ]/g, '');
  }
  var normNames = {};
  ids.forEach(function (id) { normNames[id] = norm(STATIONS[id].name); });

  function render(list) {
    shown = list;
    cursor = list.length ? 0 : -1;
    if (!list.length) {
      results.innerHTML = '<li class="empty">No station of that name</li>';
    } else {
      results.innerHTML = list.map(function (id, i) {
        var pips = STATIONS[id].lines.map(function (l) {
          return '<span class="pip" style="background:' + LINES[l].colour + '"></span>';
        }).join('');
        return '<li role="option" data-id="' + id + '" aria-selected="' +
          (i === 0) + '">' + esc(STATIONS[id].name) +
          '<span class="pips">' + pips + '</span></li>';
      }).join('');
    }
    results.hidden = false;
    search.setAttribute('aria-expanded', 'true');
  }

  function filter(q) {
    var n = norm(q);
    if (!n) return order.slice(0, 40);
    var starts = [], words = [], contains = [];
    ids.forEach(function (id) {
      var nm = normNames[id];
      var at = nm.indexOf(n);
      if (at === 0) starts.push(id);
      else if (at > 0 && nm[at - 1] === ' ') words.push(id);
      else if (at > 0) contains.push(id);
    });
    function byName(a, b) { return STATIONS[a].name < STATIONS[b].name ? -1 : 1; }
    return starts.sort(byName).concat(words.sort(byName), contains.sort(byName)).slice(0, 40);
  }

  function moveCursor(d) {
    if (!shown.length) return;
    cursor = (cursor + d + shown.length) % shown.length;
    Array.prototype.forEach.call(results.children, function (li, i) {
      li.setAttribute('aria-selected', i === cursor);
      if (i === cursor) li.scrollIntoView({ block: 'nearest' });
    });
  }

  search.addEventListener('focus', function () { render(filter(search.value)); });
  search.addEventListener('input', function () {
    combo.classList.toggle('filled', !!search.value);
    render(filter(search.value));
  });
  search.addEventListener('keydown', function (ev) {
    if (ev.key === 'ArrowDown') { ev.preventDefault(); moveCursor(1); }
    else if (ev.key === 'ArrowUp') { ev.preventDefault(); moveCursor(-1); }
    else if (ev.key === 'Enter') {
      ev.preventDefault();
      if (cursor >= 0 && shown[cursor]) choose(shown[cursor]);
    } else if (ev.key === 'Escape') {
      results.hidden = true; search.blur();
    }
  });
  results.addEventListener('mousedown', function (ev) {
    var li = ev.target.closest('li[data-id]');
    if (li) { ev.preventDefault(); choose(li.dataset.id); }
  });
  clearBtn.addEventListener('click', function () {
    search.value = ''; combo.classList.remove('filled'); search.focus();
  });
  document.addEventListener('click', function (ev) {
    if (!combo.contains(ev.target)) results.hidden = true;
  });

  function choose(id) {
    search.value = STATIONS[id].name;
    combo.classList.add('filled');
    results.hidden = true;
    goTo(id);
  }

  /* ------------------------------------------------------------------
   * Map interaction
   * ---------------------------------------------------------------- */

  var drag = null;
  svg.addEventListener('pointerdown', function (ev) {
    anim = null;
    drag = { x: ev.clientX, y: ev.clientY, moved: false };
    svg.setPointerCapture(ev.pointerId);
    svg.classList.add('dragging');
  });
  svg.addEventListener('pointermove', function (ev) {
    if (!drag) return;
    var dx = ev.clientX - drag.x, dy = ev.clientY - drag.y;
    if (Math.abs(dx) + Math.abs(dy) > 3) drag.moved = true;
    view.cx -= dx * unitsPerPx;
    view.cy -= dy * unitsPerPx;
    drag.x = ev.clientX; drag.y = ev.clientY;
    applyCam();
  });
  function endDrag(ev) {
    if (!drag) return;
    drag = null;
    svg.classList.remove('dragging');
    if (ev && ev.pointerId !== undefined) {
      try { svg.releasePointerCapture(ev.pointerId); } catch (e) {}
    }
  }
  svg.addEventListener('pointerup', endDrag);
  svg.addEventListener('pointercancel', endDrag);

  svg.addEventListener('wheel', function (ev) {
    ev.preventDefault();
    anim = null;
    var cw = svg.clientWidth, ch = svg.clientHeight;
    var factor = Math.exp(ev.deltaY * 0.0016);
    var w2 = Math.max(6, Math.min(overviewWidth() * 1.6, view.w * factor));
    /* keep the point under the cursor fixed */
    var mx = (ev.clientX / cw - 0.5), my = (ev.clientY / ch - 0.5);
    var h = view.w * ch / cw, h2 = w2 * ch / cw;
    view.cx += mx * (view.w - w2);
    view.cy += my * (h - h2);
    view.w = w2;
    applyCam();
  }, { passive: false });

  /* ------------------------------------------------------------------
   * Switching between the two layouts
   *
   * The stations slide from where they really are to where Beck would have
   * put them (or back), which makes the relationship between the two legible
   * in a way that a hard cut does not.
   * ---------------------------------------------------------------- */

  var layoutBtn = document.getElementById('btn-layout');
  var morphing = false;

  function setLayout(mode) {
    if (mode === layoutMode || morphing) return;
    morphing = true;
    if (running) { frameJobs.length = 0; running = null; endTravelStyling(); }
    clearRoute();
    if (journeyBox) journeyBox.hidden = true;

    var from = {}, to = LAYOUTS[mode];
    ids.forEach(function (id) { from[id] = { x: P[id].x, y: P[id].y }; });

    var wasOverview = view.w > overviewWidth() * 0.75;
    var anchor = wasOverview ? null : current;
    var targetW = wasOverview ? null : LAYOUT_STEP[mode] * STATION_ZOOM[mode];
    var w0 = view.w;
    var t0 = performance.now(), ms = 1600;
    layoutMode = mode;
    stationW = LAYOUT_STEP[mode] * STATION_ZOOM[mode];
    layoutBtn.textContent = mode === 'schematic' ? 'Geographic' : 'Schematic';
    anim = null;

    frameJobs.push(function (now) {
      var p = Math.min(1, (now - t0) / ms);
      var e = p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2;
      ids.forEach(function (id) {
        P[id].x = from[id].x + (to[id].x - from[id].x) * e;
        P[id].y = from[id].y + (to[id].y - from[id].y) * e;
        dots[id].setAttribute('cx', P[id].x);
        dots[id].setAttribute('cy', P[id].y);
      });
      /* straight edges while things are moving; proper routing once settled */
      buildGeometry(p >= 1 && mode === 'schematic');
      drawTransfers();
      bounds = computeBounds();
      lastSpread = -1;                       // force the edges to be redrawn

      if (anchor) {
        view.cx = P[anchor].x; view.cy = P[anchor].y;
        view.w = w0 * Math.pow(targetW / w0, e);
        parkTrain(anchor);          /* the train rides the move too */
      } else {
        var ov = overview();
        view.cx = ov.cx; view.cy = ov.cy; view.w = ov.w;
      }
      applyCam();
      if (p >= 1) {
        if (anchor) parkTrain(anchor);
        morphing = false;
        return false;
      }
      return true;
    });
  }

  layoutBtn.addEventListener('click', function () {
    setLayout(layoutMode === 'schematic' ? 'geographic' : 'schematic');
  });

  /* ------------------------------------------------------------------
   * Buttons
   * ---------------------------------------------------------------- */

  document.getElementById('btn-overview').addEventListener('click', function () {
    tweenTo(overview(), 1400);
  });
  document.getElementById('btn-random').addEventListener('click', function () {
    var id;
    do { id = ids[Math.floor(Math.random() * ids.length)]; } while (id === current);
    choose(id);
  });

  var legend = document.getElementById('legend');
  legend.innerHTML = Object.keys(LINES).map(function (k) {
    return '<div><i style="background:' + LINES[k].colour + '"></i>' +
      esc(LINES[k].name) + '</div>';
  }).join('');
  document.getElementById('btn-legend').addEventListener('click', function () {
    legend.hidden = !legend.hidden;
    this.setAttribute('aria-expanded', String(!legend.hidden));
  });

  window.addEventListener('resize', applyCam);

  /* ------------------------------------------------------------------
   * Curtain up
   * ---------------------------------------------------------------- */

  window.tube = { goTo: goTo, ids: ids, route: route, view: function () { return view; } };

  layoutBtn.textContent = layoutMode === 'schematic' ? 'Geographic' : 'Schematic';
  view = overview();
  applyCam();
  setTimeout(function () { if (!current) hint.classList.add('show'); }, 900);

  setTimeout(function () {
    if (current) return;               // the viewer got there first
    var id = ids[Math.floor(Math.random() * ids.length)];
    search.value = STATIONS[id].name;
    combo.classList.add('filled');
    goTo(id);
  }, 2800);

})();
